AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test-app

  Sample SAM Template for sam-test-app

Resources:
  # StockTradingStateMachine:
  #   Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
  #   Properties:
  #     DefinitionUri: statemachine/stock_trader.asl.json
  #     DefinitionSubstitutions:
  #       StockCheckerFunctionArn: !GetAtt StockCheckerFunction.Arn
  #       StockSellerFunctionArn: !GetAtt StockSellerFunction.Arn
  #       StockBuyerFunctionArn: !GetAtt StockBuyerFunction.Arn
  #       DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
  #       DDBTable: !Ref TransactionTable
  #     Events:
  #       HourlyTradingSchedule:
  #         Type: Schedule # More info about Schedule Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-statemachine-schedule.html
  #         Properties:
  #           Description: Schedule to run the stock trading state machine every hour
  #           Enabled: False # This schedule is disabled by default to avoid incurring charges.
  #           Schedule: "rate(1 hour)"
  #     Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
  #       - LambdaInvokePolicy:
  #           FunctionName: !Ref StockCheckerFunction
  #       - LambdaInvokePolicy:
  #           FunctionName: !Ref StockSellerFunction
  #       - LambdaInvokePolicy:
  #           FunctionName: !Ref StockBuyerFunction
  #       - DynamoDBWritePolicy:
  #           TableName: !Ref TransactionTable

  EurlexLoadNoticesStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachine/eurlex_notice.asl.json
      DefinitionSubstitutions:
        IngestAlerterArn: !GetAtt IngestAlerter.Arn
        IngestAlertFilterArn: !GetAtt IngestAlertFilter.Arn

  EurlexDocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: eurlex_documents
      KeySchema:
        - AttributeName: cellarId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: cellarId
          AttributeType: S


  IngestAlerter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ingest-alerter/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Timeout: 10

  IngestAlertFilter:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/ingest-alert-filter/
      Handler: app.lambda_handler
      Runtime: python3.8
    DependsOn:
      - EurlexDocumentsTable

Outputs:
  # StockTradingStateMachineHourlyTradingSchedule is an implicit Schedule event rule created out of Events key under Serverless::StateMachine
  # Find out more about other implicit resources you can reference within SAM
  # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-generated-resources.html
  StockTradingStateMachineArn:
    Description: "Stock Trading state machine ARN"
    Value: !Ref StockTradingStateMachine
  StockTradingStateMachineRole:
    Description: "IAM Role created for Stock Trading state machine based on the specified SAM Policy Templates"
    Value: !GetAtt StockTradingStateMachineRole.Arn
